# -*- restclient -*-

#
# Helthcheck
#

GET http://127.0.0.1:8081/api/v1/healthcheck

#
# Add documentclass
#
POST http://127.0.0.1:8081/api/v1/documentclass
Content-Type: application/json
{ "file": "https://raw.githubusercontent.com/mediocrehacker/mentaldesk/main/src/app/content/worksheets/povedencheskij-ehksperiment-list/worksheet.cls"
}

#
# Convert to pdf
#
POST http://127.0.0.1:8081/api/v1/conversion
Content-Type: application/json
{ "cls": "27742bb317dffe1fece3003ec7b2fe8ce0c66b8b62dbf1bcbc19ec90c26bc235"
, "tex": "https://raw.githubusercontent.com/mediocrehacker/mentaldesk/main/src/app/content/worksheets/povedencheskij-ehksperiment-list/worksheet.tex"
, "customization":
  { "clinicName": "Название Вашей Клиники",
    "therapist": "Фамилия Имя Специалиста",
    "email": "email@mail.ru",
    "phone": "+7-999-333-22-11",
    "client": "Фамилия Имя Клиента"
  }
}

#
# Convert to pdf
#

# GET http://localhost:8081/api/v1/static/5fea29a1a384d363c27f18895a0fae69e07142ce700d6a50a1de83aa02eaa0b2.pdf

GET http://127.0.0.1:8081/api/v1/static/59e58cf71b521e5af998ed84805d101a2a810b6158f29b62e9130d8b41c634a3e.pdf
